logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:sqlite:./spring-boot-3/spring-boot-3-flyway/src/main/resources/sample.db
    password: sample
    username: sample
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration,classpath:com/slusarz/sandbox/springboot/flyway/migrations
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
