<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.slusarz.mavenplugin</groupId>
    <artifactId>module-sample</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.source>17</maven.compiler.source>
    </properties>

    <modules>
        <module>services</module>
        <module>application</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.slusarz.mavenplugin</groupId>
            <artifactId>annotations</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.slusarz.mavenplugin</groupId>
                <artifactId>maven-plugin-sample</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <id>aggregate</id>
                        <goals>
                            <goal>aggregate-plugin</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>/docs/generated</outputDirectory>
                            <aggregates>
                                <aggregate>
                                    <inputDirectory>/doc/sample</inputDirectory>
                                    <name>sample</name>
                                    <level>1</level>
                                </aggregate>
                            </aggregates>
                        </configuration>
                    </execution>
                    <execution>
                        <id>class-scan</id>
                        <goals>
                            <goal>class-scan</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>